CREATE DATABASE QUANLISV

GO -- DOC TU TREN XUONG VI SQL CHAY CAC DONG LENH DONG THOI
USE QUANLISV
-- XOA: DROP DATABASE 
--NEU K NHAP GI CAC KI TU CON LAI CUA CHAR LA 0, ĐỂ N TRK DE NHAP TIENG VIET
CREATE TABLE SINHVIEN(
	MASV CHAR(5)NOT NULL,--PK
	HOTEN NVARCHAR(30)

)
--TAO KHOA CHINH NGOAI BANG
--LUU Y: PHAI DE NOT NULL ATTRIBUTE KHI TAO PK
GO
ALTER TABLE dbo.SINHVIEN
ADD CONSTRAINT PK_SINHVIEN --TAO RANG BUOC
PRIMARY KEY (MASV)

DROP TABLE SINHVIEN
--TAO KHOA CHINH TRONG BANG
CREATE TABLE LOPHOC(
	MALOP CHAR(5)NOT NULL,--PK
	TENLOP NVARCHAR(30),
	CONSTRAINT PK_LOPHOC --CO THE CO HOAC KHONG DE QUAN LI KHOA
	PRIMARY KEY (MALOP)
)

CREATE TABLE GIAOVIEN(
	MAGV CHAR(5)NOT NULL,--PK
	HOTEN NVARCHAR(30),
	GIOITINH NVARCHAR(10) CHECK(GIOITINH IN ('NAM', N'NỮ')),
	--CONSTRAINT PK_GV --CO THE CO HOAC KHONG DE QUAN LI KHOA
	PRIMARY KEY (MAGV)
)

--SUA TRONG BANG
GO
ALTER TABLE dbo.GIAOVIEN --VAO TABLE XOA CONSTRAINT ĐI
ALTER COLUMN GIOITINH NVARCHAR(10)

ALTER TABLE dbo.GIAOVIEN
ADD CONSTRAINT CK_GIOITINH --THEM RANG BUOC
CHECK(GIOITINH IN (N'NAM', N'FEMALE'))

DROP TABLE GIAOVIEN
--XOA CONSTRAINT 
ALTER TABLE DBO.GIAOVIEN
DROP CONSTRAINT CK_GIOITINH

CREATE TABLE GIAOVIEN(
	MAGV CHAR(5)NOT NULL,--PK
	HOTEN NVARCHAR(30),
	GIOITINH VARCHAR(10) CHECK(GIOITINH IN ('NAM', N'FEMALE')),
	--CONSTRAINT PK_GV --CO THE CO HOAC KHONG DE QUAN LI KHOA
	PRIMARY KEY (MAGV)
)

--SUA KIEU DL CUA THUOC TINH TRONG BANG
GO
ALTER TABLE dbo.GIAOVIEN --VAO TABLE XOA CONSTRAINT ĐI
ALTER COLUMN GIOITINH NVARCHAR(10)
GO
ALTER TABLE dbo.GIAOVIEN
ADD CONSTRAINT CK_GIOITINH --THEM RANG BUOC
CHECK(GIOITINH IN (N'NAM', N'NỮ'))--PHAI DAT N TRƯỚC ĐỂ TRÁNH LỖI

--THEM XOA THUOC TINH
ALTER TABLE dbo.GIAOVIEN
ADD SDT CHAR(10)

ALTER TABLE dbo.GIAOVIEN
DROP COLUMN SDT 

--KHOA NGOAI
CREATE TABLE KHOA(
MaKhoa CHAR(5),
TENKHOA NVARCHAR(50),

PRIMARY KEY(MAKHOA)
)

ALTER TABLE dbo.GIAOVIEN
ADD MAKHOA CHAR(5) --CO CUNG KIEU VS KHOA NGOAI

ALTER TABLE dbo.GIAOVIEN
ADD CONSTRAINT FK_GV_KHOA
FOREIGN KEY (MAKHOA)
REFERENCES dbo.KHOA(MaKhoa)

--CHEN DU LIEU VAO TRONG BANG
INSERT INTO KHOA(MaKhoa, TENKHOA)
VALUES ('1', 'TOÁN')
INSERT INTO KHOA(MaKhoa, TENKHOA)
VALUES ('2', 'CNTT')
INSERT INTO KHOA(MaKhoa, TENKHOA)
VALUES ('3', 'HÓA')

DROP TABLE SINHVIEN
CREATE TABLE SINHVIEN(
	MASV CHAR(5) NOT NULL,
	HOTEN NVARCHAR(50),
	)

GO 
ALTER TABLE dbo.SINHVIEN
ADD CONSTRAINT PK_SINHVIEN --TAO RANG BUOC
PRIMARY KEY (MASV)
GO 
ALTER TABLE dbo.SINHVIEN
ADD NGAYSINH DATE

GO
 -- KHI CHÈN VÀO THÔNG TIN PHẢI ĐỦ VÀ CÓ N'' TRK UNICODE 
INSERT INTO SINHVIEN
VALUES ('1', N'A', NULL)
INSERT INTO SINHVIEN
VALUES ('2', N'B', NULL)
INSERT INTO SINHVIEN
VALUES ('3', N'C', NULL)
INSERT INTO SINHVIEN
VALUES ('4', N'D', '12/1/2016')

--XEM VA XOA

GO
SELECT MASV, HOTEN, NGAYSINH
FROM SINHVIEN --FROM ĐỂ TRK CHO DỄ

GO
SELECT * -- in het
FROM SINHVIEN --FROM ĐỂ TRK CHO DỄ
--WHERE DIEU KIEN LA GI
WHERE MONTH(NGAYSINH) = 12 --dau <> 
DROP TABLE SINHVIEN
GO
UPDATE SINHVIEN
SET NGAYSINH = '1/1/2001'
--WHERE NGAYSINH = '12/1/2016'
WHERE NGAYSINH IS NULL

--MM/DD/YYYY

------khoa-----
SELECT *
FROM KHOA --FROM ĐỂ TRK CHO DỄ
WHERE MaKhoa = '3' 

INSERT INTO KHOA
VALUES ('4', 'SINH')
GO
SELECT *
FROM KHOA --FROM ĐỂ TRK CHO DỄ
--XOA
DELETE FROM KHOA
WHERE MaKhoa = 4

----------INSERT SINHVIEN----------
CREATE TABLE SINHVIEN1(
MaKhoa CHAR(5) NOT NULL,
TENKHOA NVARCHAR(50),

PRIMARY KEY(MAKHOA)
) 

GO
INSERT INTO SINHVIEN1
VALUES ('1', 'A')
INSERT INTO SINHVIEN1
VALUES ('2', 'B')
INSERT INTO SINHVIEN1
VALUES ('3', 'C')

-----------------
-- MUỐN NHẬP TEXT UNICODE DÔ PHẢI ĐỂ CHỮ N TRƯỚC ''
CREATE TABLE LOPHOC(
	MALOP CHAR(5)NOT NULL,--PK
	TENLOP NVARCHAR(50),
	PRIMARY KEY (MALOP)
)
GO
INSERT INTO LOPHOC
VALUES ('1', N'Lớp 1')
INSERT INTO LOPHOC
VALUES ('2', N'Lớp 2')
INSERT INTO LOPHOC
VALUES ('3', N'Lớp 3')

----************** CÁCH TRAO QUYỀN ĐỂ TRUY CẬP VÀO DATABASE
--CHUỘT PHẢI CHỌN PROPERIES / FILE / BROWERS / CLICK ALL => CẤP QUYỀN
--KHI KÉO KHÓA NGOÀI Ở CHỖ DELETE VÀ UPDATE RILE NHỚ CHỌN CASCADE ĐỂ KHI XÓA TRÁNH DƯ THỪA DATA

SELECT * FROM GIAOVIEN
SELECT * FROM KHOA

SELECT GV.MAGV, GV.HOTEN, K.TENKHOA
FROM GIAOVIEN GV, KHOA K
--WHERE GV.MAKHOA = K.MaKhoa --LIEN KET 2 BANG LAY RA GV + TEN KHOA
WHERE K.TENKHOA = 'CNTT' AND GV.MAKHOA = K.MaKhoa

-- SO SANH CHUOI VA CAC CAC PHEP TOAN SO HOC
SELECT *
FROM KHOA
--WHERE TENKHOA LIKE N'TOÁNN' ESCAPE 'N'--LOẠI BỎ KÍ TỰ THỪA
--WHERE TENKHOA LIKE '%T'
WHERE TENKHOA LIKE '__A' 
